create new methods to get ncbifam data
ProteinsWebTeam/pyinterprod pull request #19
Opened 2023-01-26 13:56 UTC by laisecf

to manual test run:

il = get_all_ids_list()
print(f"returned {len(il)} ids")
al = get_all_accessions_list(list(il))
print(f"returned {len(al)} accessions")
get_ncbifam_json(al)
print("json saved")

2023-01-26 17:25 UTC, matthiasblum requested changes
Nice job! :+1: 

I made a few comments where code can be improved. Let me know if it's clear enough (or if you disagree :wink:)

2023-01-26 17:25 UTC, matthiasblum commented on pyinterprod/interpro/contrib/ncbifam.py
> +        futures_to_data = {executor.submit(request.urlopen, i): i for i in url_list}
I'd prefer the function called by the executor to perform the request **and** parse the response.

2023-01-26 17:25 UTC, matthiasblum commented on pyinterprod/interpro/contrib/ncbifam.py
> +                futures_to_data.pop(future)
A few things can be improved/simplified here:

- I don't think it's necessary to keep track of the number of successful tasks. `while futures_to_data` should be enough.
- We should expect a non-significant number of failures. To avoid drowning in log messages, you remove the call to `logger.info()`.
- However, we only want ignore errors and retry, if the request fails because we already submitted too many requests (in which case, the response would have a 429 HTTP code). If the request fails for any other reason, we should just stop the script.
- I know it's good practice to define small functions, but `_retry()` is so small I don't think it's necessary to keep its content in a separate function.

2023-01-26 17:25 UTC, matthiasblum commented on pyinterprod/interpro/contrib/ncbifam.py
> +    return json_string
Better returning a dictionary, and calling `json.dumps()` in the main function.

2023-01-26 17:25 UTC, matthiasblum commented on pyinterprod/interpro/contrib/ncbifam.py
> +def _fetch_url_xml(url: str) -> xmlET:
Technically, it does not return `xmlET` but `xmlET.Element`.

2023-01-26 20:11 UTC, laisecf commented on pyinterprod/interpro/contrib/ncbifam.py
> +    return json_string
make sense! it's most userful this return

2023-01-26 20:26 UTC, laisecf commented on pyinterprod/interpro/contrib/ncbifam.py
> +        r = _fetch_url_xml(f"{BASE_ACCESSIONS_URL}&id={','.join(ids_list[i:i+step])}")
I tried to escape this 😄  I'm going to do that, it should be even faster

2023-01-26 20:29 UTC, laisecf commented on pyinterprod/interpro/contrib/ncbifam.py
> +def get_ncbifam_info(accessions_list: set):
my bad! forgot to change

2023-01-27 10:59 UTC, laisecf commented on pyinterprod/interpro/contrib/ncbifam.py
> +        r = _fetch_url_xml(f"{BASE_ACCESSIONS_URL}&id={','.join(ids_list[i:i+step])}")
I changed to POST but I will submit 500 IDs because this note:

Note: When using accession.version identifiers, there is a conversion step that takes place that causes large lists of identifiers to time out, even when using POST. Therefore, we recommend batching these types of requests in sizes of about 500 UIDs or less, to avoid retrieving only a partial amount of records from your original POST input list.

2023-02-07 12:21 UTC, matthiasblum commented on pyinterprod/interpro/contrib/ncbifam.py
> +        print(e.code)
```suggestion
```

2023-02-23 14:30 UTC, matthiasblum approved these changes
Looks good to me. Feel free to merge. :+1:

2023-02-23 15:08 UTC, merged