add update abstract to signature
ProteinsWebTeam/pyinterprod pull request #20
Opened 2023-02-22 17:34 UTC by laisecf

2023-02-23 15:07 UTC, laisecf commented on pyinterprod/interpro/signature.py
> +def update_method2pub(cur: cx_Oracle.Cursor, new_entries: list):
Maybe here its better try to insert and `pass` in case of IntegrityError than this way (making query, taking the difference and then insert). What you think?

2023-02-28 15:02 UTC, matthiasblum requested changes
This a good start. Thanks!
I've commented a few things that could be improved.

However, I realised  that we cannot update `METHOD2PUB` at this stage because of a foreign key to `METHOD`: adding records in `METHOD2PUB` for any new signature not yet in `METHOD`) will fail.

2023-02-28 15:43 UTC, laisecf commented on pyinterprod/interpro/signature.py
> +    pmids = re.findall('PMID:\s*[0-9]+', str(abstract))
Right!! Was because I had problems with the oracle LOB type in the code that update the entire table (its not the case here, I will remove) o/

2023-02-28 15:47 UTC, laisecf commented on pyinterprod/interpro/signature.py
> +    )
I have a point here!! haha Was better for the pipeline (when we get the new citations we can call again). But you right, I can change the flow to put everything in a dict and try to update again in the end.

2023-02-28 16:19 UTC, laisecf commented on pyinterprod/interpro/signature.py
> +    )
You right!!! I will put outside

2023-03-01 15:09 UTC, laisecf commented on pyinterprod/interpro/signature.py
> +        pmid = int(pmid.split(':')[1].strip())
My discovery of the year that we can return only what we put in parentheses on regex findall haha 🪄

2023-03-03 15:31 UTC, laisecf commented on pyinterprod/interpro/signature.py
> +            new_method2pub.append(tuple((pub_id, method.method_ac)))
just add again (if already in abstract) because later it will be a set(), before insertions

2023-03-07 09:28 UTC, matthiasblum requested changes
Getting there! :muscle:  
Please see my comments/suggestions.

2023-03-07 09:28 UTC, matthiasblum commented on pyinterprod/interpro/signature.py
> +
In order to keep `METHOD2PUB` indexes and foreign keys, maybe we could:
1. truncate `METHOD2PUB`
2. populate it with all rows from `METHOD2PUB_STG`

2023-03-07 09:28 UTC, matthiasblum commented on pyinterprod/interpro/signature.py
> +        )
The issue with this approach is that old references won't be deleted. 
A possible workaround is to create `METHOD2PUB_STG` empty, keep all rows from `METHOD2PUB` in memory (dictionary accession -> set of publication IDs), but overwriting the value in `update_references()`, then populating `METHOD2PUB_STG`.

2023-03-07 09:46 UTC, laisecf commented on pyinterprod/interpro/signature.py
> +
you right!!

2023-03-08 16:20 UTC, matthiasblum requested changes
A few more changes to make :wink:

2023-03-08 16:20 UTC, matthiasblum commented on pyinterprod/interpro/signature.py
> +def update_references(cur: cx_Oracle.Cursor, method,
`method`'s type is missing.

2023-03-08 16:20 UTC, matthiasblum commented on pyinterprod/interpro/signature.py
> +    return pub_id
```suggestion
        return pub_id
    else:
        logger.warning(f"Citation related to PMID {pmid} not found.")
        return None
```

2023-03-08 16:20 UTC, matthiasblum commented on pyinterprod/interpro/signature.py
> +    )
You can use `ora.truncate_table()` (with `reuse_storage=True`)

https://github.com/ProteinsWebTeam/pyinterprod/blob/c56270b897035b49b43180ff31425e571d293ce6/pyinterprod/utils/oracle.py#L263-L269

2023-03-10 08:54 UTC, laisecf commented on pyinterprod/interpro/signature.py
> +                pmid2pubid.update({pmid: pub_id})
the integrity problem was caused by the new citations that were added (occurred when there was more than one abstract to be updated with the same pmid). Resolution: update pmid2pubid when adding

2023-03-14 08:50 UTC, matthiasblum requested changes
Two suggestions made in `update_method2pub()` and two made in `update_references()`.

Also, I don't think we need `new_method2pub`: it is passed to `update_references()`, in which it's updated, then whatever is there is assigned to `method2pub[m.accession]`. I think we refactor `update_references()` to return a set of publication IDs and assign the result to `method2pub[m.accession]`.

2023-03-14 08:50 UTC, matthiasblum commented on pyinterprod/interpro/signature.py
> +    method_ids = [i for sublist in [[(m, pmid) for pmid in pmdis] for m, pmdis in method2pub.items()] for i in sublist]
This can be greatly be simplified. Also, the order of the elements in tuples matter. The SQL query below is `INSERT INTO INTERPRO.METHOD2PUB_STG (PUB_ID, METHOD_AC)`, therefore, tuples must be `(pmid, accession)`.

```suggestion
    data = [(pmid, acc) for acc, pmids in method2pub.items() for pmid in pmids]
```

2023-03-14 08:50 UTC, matthiasblum commented on pyinterprod/interpro/signature.py
> +    )
Oracle may raise an error if there are _too many_ rows being inserted at the same time (not sure what is the limit), so we can insert rows by chunks of 1k:

```suggestion
    step = 1000
    for i in range(0, len(data), step):
        cur.executemany(
            """
            INSERT INTO INTERPRO.METHOD2PUB_STG (PUB_ID, METHOD_AC)
            VALUES (:1, :2)
            """,
            data[i:i+step]
        )
```

2023-03-14 08:50 UTC, matthiasblum commented on pyinterprod/interpro/signature.py
> +                pmid2pubid.update({pmid: pub_id})
```suggestion
                pmid2pubid[pmid] = pub_id
```

2023-03-14 08:50 UTC, matthiasblum commented on pyinterprod/interpro/signature.py
> +            pmid2pubid.update({pmid: pub_id})
```suggestion
            pmid2pubid[pmid] = pub_id
```

2023-03-14 14:22 UTC, matthiasblum requested changes

2023-03-14 14:22 UTC, matthiasblum commented on pyinterprod/interpro/signature.py
> +                new_method2pub.append(pub_id)
```suggestion
                pub_ids.add(pub_id)
```

2023-03-14 15:46 UTC, matthiasblum commented
I've also mentioned something in `update_references()`. The abstract is updated with the PMID replaced by the publication ID:

https://github.com/ProteinsWebTeam/pyinterprod/blob/b6c0ce5302fd112974c332e15bc9eb74cd3cd5f7/pyinterprod/interpro/signature.py#L614-L616

However, the regular expression allows spaces _after_ "PMID:"

https://github.com/ProteinsWebTeam/pyinterprod/blob/b6c0ce5302fd112974c332e15bc9eb74cd3cd5f7/pyinterprod/interpro/signature.py#L606

So if an abstract contains `[PMID: 12345]`, it's going to be picked up by the regular expression, but the abstract won't be updated. A possible fix is to use `re.finditer()` which returns an iterator of matches, where the PMID can be accessed with `int(match.group(1))` and the string to replace with `match.group(0)`.

2023-03-14 15:50 UTC, matthiasblum requested changes
I noticed something in `update_references()`. 

The abstract is updated with the PMID replaced by the publication ID:

https://github.com/ProteinsWebTeam/pyinterprod/blob/b6c0ce5302fd112974c332e15bc9eb74cd3cd5f7/pyinterprod/interpro/signature.py#L614-L616

However, the regular expression allows spaces _after_ "PMID:"

https://github.com/ProteinsWebTeam/pyinterprod/blob/b6c0ce5302fd112974c332e15bc9eb74cd3cd5f7/pyinterprod/interpro/signature.py#L606

So if an abstract contains `[PMID: 12345]`, it's going to be picked up by the regular expression, but the abstract won't be updated (because `PMID:12345` won't be found). A possible fix is to use `re.finditer()` which returns an iterator of matches, where the PMID can be accessed with `int(match.group(1))` and the string to replace with `match.group(0)`.

2023-03-14 16:34 UTC, laisecf commented
> I noticed something in `update_references()`.
> 
> The abstract is updated with the PMID replaced by the publication ID:
> 
> https://github.com/ProteinsWebTeam/pyinterprod/blob/b6c0ce5302fd112974c332e15bc9eb74cd3cd5f7/pyinterprod/interpro/signature.py#L614-L616
> 
> However, the regular expression allows spaces _after_ "PMID:"
> 
> https://github.com/ProteinsWebTeam/pyinterprod/blob/b6c0ce5302fd112974c332e15bc9eb74cd3cd5f7/pyinterprod/interpro/signature.py#L606
> 
> So if an abstract contains `[PMID: 12345]`, it's going to be picked up by the regular expression, but the abstract won't be updated (because `PMID:12345` won't be found). A possible fix is to use `re.finditer()` which returns an iterator of matches, where the PMID can be accessed with `int(match.group(1))` and the string to replace with `match.group(0)`.

good eye! I will fix this o/

2023-03-15 10:46 UTC, matthiasblum approved these changes
LGTM :tada:

2023-03-15 10:46 UTC, merged