add PANTHER subfamilies info to pronto db
ProteinsWebTeam/pyinterprod pull request #25
Opened 2023-04-13 10:17 UTC by typhainepl

tested on IPDEV/intdev

2023-04-13 15:29 UTC, matthiasblum requested changes
The structure of the matches file (created in the `export-matches` task) has been changed in 8c5c30f. Any task using this file may need to be updated to reflect the changes. These tasks are:

- `insert-matches`
- `insert-signature2proteins`
- `signatures`

I looks like only `insert-signature2proteins` has been changed. Did you test `insert-matches` and `signatures`? I think they need to be updated as well.

An issue with the way matches are stored (`signature -> model -> (database, fragments))`) is that two models belonging to the same CATH-Gene3D or SUPERFAMILY signature can hit the same protein, leading to duplicated (signature, protein) pairs in `signature2protein`.

For instance:

```sql
SELECT *
FROM interpro.signature2protein
WHERE signature_acc = 'SSF158446' 
  AND protein_acc = 'A0A2X4WZ54';
```

returns:

| signature\_acc | model\_acc | protein\_acc | is\_reviewed | taxon\_left\_num | name\_id | md5 |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| SSF158446 | 0054679 | A0A2X4WZ54 | false | 1240236 | 8066 | 1fe6fc913b9a51dde6d46340e3dce694 |
| SSF158446 | 0053972 | A0A2X4WZ54 | false | 1240236 | 8066 | 1fe6fc913b9a51dde6d46340e3dce694 |

This may cause proteins matched by `SSF158446` to be counted twice when comparing signatures (taxonomic origins, UniProt descriptions, similarity comments, etc.)

I'll add the creation of a primary key on `(signature_acc, protein_acc)` in a different branch so we don't get this issue in the future.

Finally, `intdev` is one UniProt release behind `intpro`, yet `signature2protein` is ~15% bigger in `intdev`:

```sql
intpro=> SELECT pg_size_pretty(pg_relation_size('signature2protein'));
 pg_size_pretty 
----------------
 114 GB

intdev=> SELECT pg_size_pretty(pg_relation_size('signature2protein'));
 pg_size_pretty 
----------------
 131 GB
```

I am not sure how much the duplicated rows contribute to this increase, but you could the `model_acc` nullable and only add the model for PANTHER families.

2023-05-16 09:01 UTC, matthiasblum requested changes
Looks good. No big changes required, just small ones (like PEP-8).

2023-05-16 09:01 UTC, matthiasblum commented on pyinterprod/pronto/match.py
> +                matches[signature_acc] = {model_acc:(signature_db, [fragments])}
PEP-8, can be replaced by:

```py
            try:
                models = matches[signature_acc]
            except KeyError:
                models = matches[signature_acc] = {}

            try:
                models[model_acc][1].append(fragments)
            except KeyError:
                models[model_acc] = (signature_db, [fragments])
```

2023-05-16 15:23 UTC, typhainepl commented on pyinterprod/pronto/signature.py
> +                            matches[signature_acc] = sorted(merge_overlapping(hits))
No according to the following piece of code in match, model_acc is not ignore:

2023-05-16 16:55 UTC, matthiasblum commented on pyinterprod/pronto/signature.py
> +                            matches[signature_acc] = sorted(merge_overlapping(hits))
Ah yes. It's not set to `None` but to the signature accession. But that doesn't change the fact there will be only one iteration (because only one item in `matches_file[signature_acc]`.

2023-05-17 15:32 UTC, typhainepl commented on pyinterprod/pronto/match.py
> +                matches[signature_acc] = {model_acc:(signature_db, [fragments])}
if using this format, should I return the `models` variable in the yield?

2023-05-18 13:13 UTC, matthiasblum commented on pyinterprod/pronto/match.py
> +                matches[signature_acc] = {model_acc:(signature_db, [fragments])}
The yield statement should not be changed: still yielding `protein_acc, is_reviewed, is_complete, left_number, matches`.

The snipped I posted is just another way of building `matches`.

2023-05-19 08:42 UTC, merged

2023-05-19 08:43 UTC, matthiasblum commented
Looks good to be. Thanks!