track citation changes
ProteinsWebTeam/pyinterprod pull request #27
Opened 2023-05-16 13:39 UTC by laisecf

2023-05-26 13:57 UTC, matthiasblum requested changes
Thank you. 

The first step of `track_citation_changes()` is to make a hash of the citations in our database, so later we can compare them with those retrieve from LITPUB. I don't think we need to do this, and we can keep it simpler:

1. We get all publication IDs used in the database (already implemented in `_get_used_citations_pubid()`)
2. We find the PMIDs that are associated the publication IDs found above (you could modify `_get_used_citations_pubid()` so it directly returns the PMIDs
3. We import each PMID and update the `CITATION` table

And to delete all unused citations, you don't need to delete them one by one:

```sql
DELETE FROM INTERPRO.CITATION
WHERE PUB_ID NOT IN 
(
    SELECT PUB_ID FROM INTERPRO.ENTRY2PUB
    UNION
    SELECT PUB_ID FROM INTERPRO.METHOD2PUB
    UNION
    SELECT PUB_ID FROM INTERPRO.SUPPLEMENTARY_REF
)
```

2023-05-26 13:57 UTC, matthiasblum commented on pyinterprod/interpro/signature.py
> +    return set(current_citations)
- Indentation of SQL query
- No need to wrap the three subqueries
- No need to save the results in a list, then convert it to a set: we can directly create the set
- Variable name: `citations` -> `pub_id` (each element in the sequences returned by `cur.fetchall()` is a single publication ID; `citations` would be of a sequence of IDs)

```suggestion
    cur.execute(
        """
        SELECT PUB_ID FROM INTERPRO.ENTRY2PUB
        UNION
        SELECT PUB_ID FROM INTERPRO.SUPPLEMENTARY_REF
        UNION
        SELECT PUB_ID FROM INTERPRO.METHOD2PUB
        """
    )
    return {pub_id for pub_id, in cur.fetchall()}
```

2023-05-26 13:57 UTC, matthiasblum commented on pyinterprod/interpro/signature.py
> +    )
Indentation:

```suggestion
    cur.execute(
        """
        DELETE FROM INTERPRO.CITATION
        WHERE PUBMED_ID = :1
        """, 
        [str(pmid)]
    )
```

2023-05-26 13:57 UTC, matthiasblum commented on pyinterprod/interpro/signature.py
> +    )
Indentation:

```suggestion    cur.execute(
        """
        MERGE INTO INTERPRO.CITATION IC
        USING (
            SELECT DISTINCT
                C.EXTERNAL_ID AS EXTERNAL_ID, I.VOLUME AS VOLUME, I.ISSUE AS ISSUE,
                I.PUBYEAR AS YEAR, C.TITLE AS TITLE, C.PAGE_INFO AS RAWPAGES,
                J.MEDLINE_ABBREVIATION AS MEDLINE_JOURNAL, J.ISO_ABBREVIATION AS ISO_JOURNAL,
                A.AUTHORS AS AUTHORS, LOWER(REGEXP_REPLACE(U.URL, '(^[[:space:]]*|[[:space:]]*$)')) AS DOI_URL
            FROM CDB.CITATIONS@LITPUB C
            LEFT OUTER JOIN CDB.JOURNAL_ISSUES@LITPUB I
                ON C.JOURNAL_ISSUE_ID = I.ID
            LEFT JOIN CDB.CV_JOURNALS@LITPUB J
                ON I.JOURNAL_ID = J.ID
            LEFT OUTER JOIN CDB.FULLTEXT_URL_MEDLINE@LITPUB U
                ON (
                    C.EXTERNAL_ID = U.EXTERNAL_ID AND
                    UPPER(U.SITE) = 'DOI'
                )
            LEFT OUTER JOIN CDB.AUTHORS@LITPUB A
                ON (
                    C.ID = A.CITATION_ID AND
                    A.HAS_SPECIAL_CHARS = 'N'
                )
        ) L
        ON (TO_CHAR(IC.PUBMED_ID) = L.EXTERNAL_ID)
        WHEN MATCHED THEN
            UPDATE SET IC.VOLUME = L.VOLUME,
            IC.ISSUE = L.ISSUE,
            IC.YEAR = L.YEAR,
            IC.TITLE = L.TITLE,
            IC.RAWPAGES = L.RAWPAGES,
            IC.MEDLINE_JOURNAL = L.MEDLINE_JOURNAL,
            IC.ISO_JOURNAL = L.ISO_JOURNAL,
            IC.AUTHORS = L.AUTHORS,
            IC.DOI_URL = L.DOI_URL
            WHERE PUBMED_ID = :1
        """,
        [pmid]
    )
```

2023-07-14 13:23 UTC, matthiasblum requested changes
Almost there. Most changes are to be PEP-8 compliant (80 characters/line max). One comment is to change the return type.

2023-07-14 13:23 UTC, matthiasblum commented on pyinterprod/interpro/signature.py
> +        )
```suggestion
        cur.executemany(
            """
            UPDATE INTERPRO.CITATION
                SET VOLUME= :1, 
                    ISSUE= :2, 
                    YEAR= :3, 
                    TITLE= :4, 
                    RAWPAGES= :5, 
                    MEDLINE_JOURNAL= :6, 
                    ISO_JOURNAL= :7, 
                    AUTHORS= :8, 
                    DOI_URL= :9
            WHERE PUBMED_ID = :10
            """, 
            citations
        )
```

2023-07-14 13:23 UTC, matthiasblum commented on pyinterprod/interpro/signature.py
> +                    J.MEDLINE_ABBREVIATION AS MEDLINE_JOURNAL, J.ISO_ABBREVIATION AS ISO_JOURNAL,
```suggestion
            SELECT VOLUME, ISSUE, YEAR, TITLE, RAWPAGES, MEDLINE_JOURNAL, 
                   ISO_JOURNAL, AUTHORS, DOI_URL, EXTERNAL_ID
            FROM (
                SELECT
                    C.EXTERNAL_ID AS EXTERNAL_ID, I.VOLUME AS VOLUME, 
                    I.ISSUE AS ISSUE, I.PUBYEAR AS YEAR, C.TITLE AS TITLE, 
                    C.PAGE_INFO AS RAWPAGES, 
                    J.MEDLINE_ABBREVIATION AS MEDLINE_JOURNAL, 
                    J.ISO_ABBREVIATION AS ISO_JOURNAL,
```

2023-07-14 13:23 UTC, matthiasblum commented on pyinterprod/interpro/signature.py
> +    return {str(pmid) for pmid, in cur.fetchall()}
There is a unique key on `PUBMED_ID` in `INTERPRO.CITATION` so we can return a list directly and there won't be duplicated IDs:

```suggestion
def _get_used_citations_pmids(cur: cx_Oracle.Cursor) -> list[str]:
    cur.execute(
        """
        SELECT PUBMED_ID
        FROM INTERPRO.CITATION
        WHERE PUB_ID IN (
            SELECT PUB_ID FROM INTERPRO.ENTRY2PUB
            UNION
            SELECT PUB_ID FROM INTERPRO.SUPPLEMENTARY_REF
            UNION
            SELECT PUB_ID FROM INTERPRO.METHOD2PUB
        )
        """
    )
    return [str(pmid) for pmid, in cur.fetchall()]
```

2023-07-14 13:23 UTC, matthiasblum commented on pyinterprod/interpro/signature.py
> +        params = list(pmids)[i: i + step]
I made a suggestion below for `_get_used_citations_pmids()` to return a list instead of a set, so:

```suggestion
    pmids = _get_used_citations_pmids(cur)
    step = 1000
    for i in range(0, len(pmids), step):
        params = pmids[i:i+step]
```

2023-07-14 13:23 UTC, matthiasblum commented on pyinterprod/interpro/signature.py
> +        SELECT EXTERNAL_ID, VOLUME, ISSUE, YEAR, TITLE, RAWPAGES, MEDLINE_JOURNAL, ISO_JOURNAL, AUTHORS, DOI_URL
```suggestion
        SELECT EXTERNAL_ID, VOLUME, ISSUE, YEAR, TITLE, RAWPAGES, 
               MEDLINE_JOURNAL, ISO_JOURNAL, AUTHORS, DOI_URL
```

2023-07-14 13:23 UTC, matthiasblum commented on pyinterprod/interpro/signature.py
> +                J.MEDLINE_ABBREVIATION AS MEDLINE_JOURNAL, J.ISO_ABBREVIATION AS ISO_JOURNAL,
```suggestion
                C.EXTERNAL_ID AS EXTERNAL_ID, I.VOLUME AS VOLUME, 
                I.ISSUE AS ISSUE, I.PUBYEAR AS YEAR, C.TITLE AS TITLE, 
                C.PAGE_INFO AS RAWPAGES, 
                J.MEDLINE_ABBREVIATION AS MEDLINE_JOURNAL, 
                J.ISO_ABBREVIATION AS ISO_JOURNAL,
```

2023-08-01 09:24 UTC, matthiasblum requested changes
Made a few suggestions following #30. But more changes are required (e.g. replacing `cx_Oracle` with `oracledb`)

2023-08-01 09:24 UTC, matthiasblum commented on pyinterprod/interpro/signature.py
> +    uri: str, table: str, partition: Optional[str], column: str, step: int, stop: int
```suggestion
    uri: str, table: str, partition: str |None, column: str, step: int, stop: int
```

2023-08-01 09:24 UTC, matthiasblum commented on pyinterprod/interpro/signature.py
> +    cur: cx_Oracle.Cursor, method: Method, pmid2pubid: dict[int, str]
```suggestion
    cur: oracledb.Cursor, method: Method, pmid2pubid: dict[int, str]
```

2023-08-01 09:24 UTC, matthiasblum commented on pyinterprod/interpro/signature.py
> +def import_citation(cur: cx_Oracle.Cursor, pmid: int) -> Optional[str]:
```suggestion
def import_citation(cur: oracledb.Cursor, pmid: int) -> Optional[str]:
```

2023-08-01 09:24 UTC, matthiasblum commented on pyinterprod/interpro/signature.py
> +def update_citations(cur: cx_Oracle.Cursor):
```suggestion
def update_citations(cur: oracledb.Cursor):
```

2023-08-01 09:24 UTC, matthiasblum commented on pyinterprod/interpro/signature.py
> +def _get_used_citations_pmids(cur: cx_Oracle.Cursor) -> list[str]:
```suggestion
def _get_used_citations_pmids(cur: oracledb.Cursor) -> list[str]:
```

2023-08-01 09:39 UTC, laisecf commented
> Made a few suggestions following #30. But more changes are required (e.g. replacing `cx_Oracle` with `oracledb`)

Conflicts with master (after dependences merge) solved o/ I will check if there is more changes now

2023-08-01 10:06 UTC, matthiasblum approved these changes

2023-08-01 10:06 UTC, merged