genome properties cross ref
ProteinsWebTeam/pyinterprod pull request #28
Opened 2023-05-22 13:53 UTC by laisecf

2023-05-23 11:23 UTC, matthiasblum commented on pyinterprod/interpro/contrib/gp.py
> +def import_gp(cur: cx_Oracle.Cursor, file_path: str):
It would be more accurate to rename to function `update_xrefs`. Also, pass the connection string instead of the Oracle cursor.

2023-05-23 11:28 UTC, matthiasblum commented on pyinterprod/interpro/contrib/gp.py
> +        for line in fh:
Trim the new line character of each line:

```suggestion
        for line in map(str.rstrip, fh):
```

2023-05-23 11:28 UTC, matthiasblum commented on pyinterprod/interpro/contrib/gp.py
> +                description = line.split(" ", maxsplit=1)[1].strip()
By default, `str.split()` splits on whitespaces, which is what we want here, so there is no need to pass a delimiter:

```suggestion
                description = line.split(maxsplit=1)[1]
```

2023-05-23 11:33 UTC, matthiasblum commented on pyinterprod/interpro/contrib/gp.py
> +                    gp.append((ev, "h", description, entry_ac))
I would use a regular expression:

```suggestion
                _, evidence = line.split(maxsplit=1)
                m = re.match(r"IPR\d+", evidence)
                if m:
                    gp.append((m.group(0), "h", description, entry_ac)(
```

2023-05-23 11:34 UTC, matthiasblum commented on pyinterprod/interpro/contrib/gp.py
> +    import_gp(cur, "path/to/genomeProperties.txt")
The connection string must come from a variable environment (e.g. `INTERPRO_URI`), and the flat file from a command line argument.

2023-05-24 10:36 UTC, matthiasblum requested changes
Just a few small things to change and we're good to merge :+1:

2023-05-24 17:04 UTC, laisecf commented
> Just a few small things to change and we're good to merge 👍

Ok, thank you for the improvements!! I will just run again in dev and merge o/

2023-05-24 17:41 UTC, merged