Update dependencies
ProteinsWebTeam/pyinterprod pull request #30
Opened 2023-06-09 12:45 UTC by laisecf

2023-07-14 13:55 UTC, matthiasblum requested changes
Thank you. I've added a few suggestions, mostly to comply with PEP-8 (max 80 characters/line).

It seems that the [CsvIO class](https://github.com/ProteinsWebTeam/pyinterprod/blob/95225efc686b38539c8bb31d7daa14ed5d667a34/pyinterprod/utils/pg.py#L8) is not required anymore. Please delete the implementation and imports.

Finally, can you post the run time of Pronto tasks so we can compare performances?

2023-07-14 13:55 UTC, matthiasblum commented on pyinterprod/pronto/goa.py
> +              """
```suggestion
        sql = """
            INSERT INTO protein2go 
                (protein_acc, term_id, ref_db_code, ref_db_id) 
            VALUES (%s, %s, %s, %s)
        """
```

2023-07-14 13:55 UTC, matthiasblum commented on pyinterprod/pronto/goa.py
> +        if records:
```suggestion

        if records:
```

2023-07-14 13:55 UTC, matthiasblum commented on pyinterprod/pronto/goa.py
> +              """
```suggestion
        sql = """
            INSERT INTO publication (id, title, published) 
            VALUES (%s, %s, %s)
        """
```

2023-07-14 13:55 UTC, matthiasblum commented on pyinterprod/pronto/goa.py
> +        if records:
```suggestion

        if records:
```

2023-07-14 13:55 UTC, matthiasblum commented on pyinterprod/pronto/goa.py
> +              """
```suggestion
        sql = """
            INSERT INTO term 
                (id, name, category, num_constraints, is_obsolete, definition, 
                replaced_id) 
            VALUES (%s, %s, %s, %s, %s, %s, %s)
        """
```

2023-07-14 13:55 UTC, matthiasblum commented on pyinterprod/pronto/goa.py
> +            if len(records) == 1000:
```suggestion

            if len(records) == 1000:
```

2023-07-14 13:55 UTC, matthiasblum commented on pyinterprod/pronto/match.py
> +              """
```suggestion
        sql = """
            INSERT INTO signature2protein 
                (signature_acc, model_acc, protein_acc, is_reviewed, 
                taxon_left_num, name_id, md5) 
            VALUES (%s, %s, %s, %s, %s, %s, %s)
        """
```

2023-07-14 13:55 UTC, matthiasblum commented on pyinterprod/pronto/match.py
> +        if records:
```suggestion

        if records:
```

2023-07-14 13:55 UTC, matthiasblum commented on pyinterprod/pronto/match.py
> +              """
```suggestion
        sql = """
            INSERT INTO match 
                (protein_acc, signature_acc, database_id, fragments) 
            VALUES (%s, %s, %s, %s)
        """
```

2023-07-14 13:55 UTC, matthiasblum commented on pyinterprod/pronto/match.py
> +        if records:
```suggestion

        if records:
```

2023-07-14 13:55 UTC, matthiasblum commented on pyinterprod/pronto/match.py
> +              """
```suggestion
        sql = """
            INSERT INTO match 
                (protein_acc, signature_acc, database_id, fragments) 
            VALUES (%s, %s, %s, %s)
        """
```

2023-07-14 13:55 UTC, matthiasblum commented on pyinterprod/pronto/match.py
> +        if records:
```suggestion

        if records:
```

2023-07-14 13:55 UTC, matthiasblum commented on pyinterprod/pronto/protein.py
> +              """
```suggestion
        sql = """
            INSERT INTO protein_similarity 
                (comment_id, comment_text, protein_acc) 
            VALUES (%s, %s, %s)
        """
```

2023-07-14 13:55 UTC, matthiasblum commented on pyinterprod/pronto/protein.py
> +        if records:
```suggestion

        if records:
```

2023-07-14 13:55 UTC, matthiasblum commented on pyinterprod/pronto/protein.py
> +                          """
```suggestion
        sql_protein2name = """
            INSERT INTO protein2name (protein_acc, name_id) 
            VALUES (%s, %s)
        """

        sql_protein_name = """
            INSERT INTO protein_name (name_id, text) 
            VALUES (%s, %s)
        """
```

2023-07-14 13:55 UTC, matthiasblum commented on pyinterprod/pronto/protein.py
> +                    if records:
```suggestion

                    if records:
```

2023-07-14 13:55 UTC, matthiasblum commented on pyinterprod/pronto/protein.py
> +            if records:
```suggestion

            if records:
```

2023-07-14 13:55 UTC, matthiasblum commented on pyinterprod/pronto/protein.py
> +        if records:
```suggestion

        if records:
```

2023-07-14 13:55 UTC, matthiasblum commented on pyinterprod/pronto/protein.py
> +    logger.info(f"disk usage: {os.path.getsize(tmp_database) / 1024 ** 2:.0f} MB")
```suggestion
    logger.info(f"disk usage: "
                f"{os.path.getsize(tmp_database) / 1024 ** 2:.0f} MB")
```

2023-07-14 13:55 UTC, matthiasblum commented on pyinterprod/pronto/protein.py
> +              """
```suggestion
        sql = """
            INSERT INTO protein 
                (accession, identifier, length, taxon_id, is_fragment, 
                is_reviewed) 
            VALUES (%s, %s, %s, %s, %s, %s)
        """
```

2023-07-14 13:55 UTC, matthiasblum commented on pyinterprod/pronto/protein.py
> +        if records:
```suggestion

        if records:
```

2023-07-14 13:55 UTC, matthiasblum commented on pyinterprod/pronto/protein.py
> +            if len(records) == 1000:
```suggestion

            if len(records) == 1000:
```

2023-07-14 13:55 UTC, matthiasblum commented on pyinterprod/pronto/proteome.py
> +              """
```suggestion
        sql = """
            INSERT INTO proteome2protein (id, protein_acc) 
            VALUES (%s, %s)
        """
```

2023-07-14 13:55 UTC, matthiasblum commented on pyinterprod/pronto/proteome.py
> +        if records:
```suggestion

        if records:
```

2023-07-14 13:55 UTC, matthiasblum commented on pyinterprod/pronto/proteome.py
> +        if records:
```suggestion

        if records:
```

2023-07-14 13:55 UTC, matthiasblum commented on pyinterprod/pronto/proteome.py
> +              """
```suggestion
        sql = """
            INSERT INTO proteome (id, name, taxon_id, num_proteins) 
            VALUES (%s, %s, %s, %s)
        """
```

2023-07-14 13:55 UTC, matthiasblum commented on pyinterprod/pronto/signature.py
> +              """
```suggestion
        sql = """
            INSERT INTO signature 
                (accession, database_id, name, description, type, abstract, 
                num_sequences, num_reviewed_sequences, num_complete_sequences, 
                num_complete_reviewed_sequences, num_residues) 
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
        """
```

2023-07-14 13:55 UTC, matthiasblum commented on pyinterprod/pronto/signature.py
> +              """
```suggestion
        sql = """
            INSERT INTO comparison 
                (signature_acc_1, signature_acc_2, num_collocations, 
                num_overlaps) 
            VALUES (%s, %s, %s, %s)
        """
```

2023-07-14 13:55 UTC, matthiasblum commented on pyinterprod/pronto/signature.py
> +        if records:
```suggestion

        if records:
```

2023-07-14 13:55 UTC, matthiasblum commented on pyinterprod/pronto/signature.py
> +              """
```suggestion
        sql = """
            INSERT INTO prediction 
                (signature_acc_1, signature_acc_2, num_collocations, 
                num_protein_overlaps, num_residue_overlaps) 
            VALUES (%s, %s, %s, %s, %s)
        """
```

2023-07-14 13:55 UTC, matthiasblum commented on pyinterprod/pronto/signature.py
> +        if records:
```suggestion

        if records:
```

2023-07-14 13:55 UTC, matthiasblum commented on pyinterprod/pronto/taxon.py
> +              """
```suggestion
        sql = """
            INSERT INTO taxon 
                (id, name, rank, left_number, right_number, parent_id, lineage)
            VALUES (%s, %s, %s, %s, %s, %s, %s)
        """
```

2023-07-14 13:55 UTC, matthiasblum commented on pyinterprod/pronto/taxon.py
> +            records.append((tax_id, name, rank, left_num, right_num, parent_id, json_lineage))
```suggestion
        for tax_id, value in taxa.items():
            (name, rank, left_num, right_num, parent_id) = value
            json_lineage = json.dumps(get_lineage(taxa, tax_id))
            records.append((tax_id, name, rank, left_num,
                            right_num, parent_id, json_lineage))
```

2023-07-14 13:55 UTC, matthiasblum commented on pyinterprod/pronto/taxon.py
> +              """
```suggestion
        sql = """
            INSERT INTO lineage (child_id, parent_id, parent_rank) 
            VALUES (%s, %s, %s)
        """
```

2023-07-18 08:31 UTC, laisecf commented
> Thank you. I've added a few suggestions, mostly to comply with PEP-8 (max 80 characters/line).
> 
> It seems that the [CsvIO class](https://github.com/ProteinsWebTeam/pyinterprod/blob/95225efc686b38539c8bb31d7daa14ed5d667a34/pyinterprod/utils/pg.py#L8) is not required anymore. Please delete the implementation and imports.
> 
> Finally, can you post the run time of Pronto tasks so we can compare performances?


**The run with the new dependences takes more ~10h30**

**The last production run:**
![Screenshot 2023-07-17 at 16 59 32](https://github.com/ProteinsWebTeam/pyinterprod/assets/17861151/feb56bfc-2384-4964-be2c-2f2afc8da865)
                                                                                                                                         
pronto-annotations                   07 17:55:09    07 18:27:35    ~30  
pronto-taxonomy                      07 17:55:09    07 17:59:51    4min 
pronto-databases                     07 17:55:09    07 17:55:20     0   
pronto-export-matches                07 17:55:10    08 03:54:16    ~10h 
pronto-proteins-similarities         07 17:55:10    07 18:03:54    8min 
pronto-proteomes                     07 17:55:10    07 18:26:10    ~30mi
pronto-proteins                      07 17:55:10    07 18:57:35    ~1h  
pronto-init-matches                  07 17:55:10    07 17:55:17     0   
pronto-proteins-names                07 17:55:10    07 21:57:07    ~4h  
pronto-insert-fmatches               07 17:55:41    07 18:11:41    16min
pronto-insert-matches                08 03:54:32    08 04:16:14    22min
pronto-signatures                    08 03:54:32    08 05:17:50    ~1h30
pronto-insert-signature2proteins     08 03:54:32    08 04:40:17    ~1h  
pronto-index-matches                 08 04:16:20    08 08:42:47    ~4h30
pronto-index-signature2proteins      09 12:54:10    09 19:49:59    ~7h  

**The test with dependencies updated:**
![Screenshot 2023-07-17 at 16 57 43](https://github.com/ProteinsWebTeam/pyinterprod/assets/17861151/3d376d66-c883-4f96-8001-8097923659ab)
                                                            
pronto-annotations                   10 16:44:43    10 17:05:13   20min 
pronto-taxonomy                      10 16:44:43    10 16:52:55    8min 
pronto-databases                     10 16:44:44    10 16:44:49     0   
pronto-export-matches                10 16:44:44    11 02:44:01    ~10h 
pronto-proteins-similarities         10 16:44:44    10 16:49:24    5min 
pronto-proteomes                     10 16:44:44    10 17:49:49    ~1h  
pronto-proteins                      10 16:44:44    10 19:20:29    ~3h  
pronto-init-matches                  10 16:44:44    10 16:45:08     0   
pronto-proteins-names                10 16:44:44    10 20:48:29    ~4h  
pronto-insert-fmatches               10 16:45:14    10 18:02:29    ~1h  
pronto-insert-matches                11 02:44:05    11 05:34:52    ~3h  
pronto-signatures                    11 02:44:06    11 04:21:19    ~2h  
pronto-insert-signature2proteins     11 02:44:06    11 05:56:30    ~3h  
pronto-index-matches                 11 05:34:59    11 12:02:39    ~7h  
pronto-index-signature2proteins      11 05:56:34    11 13:15:23    ~7h

2023-07-18 10:56 UTC, laisecf commented
> Thank you. I've added a few suggestions, mostly to comply with PEP-8 (max 80 characters/line).
> 
> It seems that the [CsvIO class](https://github.com/ProteinsWebTeam/pyinterprod/blob/95225efc686b38539c8bb31d7daa14ed5d667a34/pyinterprod/utils/pg.py#L8) is not required anymore. Please delete the implementation and imports.
> 
> Finally, can you post the run time of Pronto tasks so we can compare performances?

The run with the executemany takes plus ~10h30

| Task Name                        | Runtime before           | Runtime after            | Difference |
|----------------------------------|--------------------------|--------------------------|------------|
| pronto-annotations               | 07/17:55:09->07/18:27:35 | 10/16:44:43->10/17:05:13 | -          |
| pronto-taxonomy                  | 07/17:55:09->07/17:59:51 | 10/16:44:43->10/16:52:55 | -          |
| pronto-databases                 | 07/17:55:09->07/17:55:20 | 10/16:44:44->10/16:44:49 | -          |
| pronto-export-matches            | 07/17:55:10->08/03:54:16 | 10/16:44:44->11/02:44:01 | -          |
| pronto-proteins-similarities     | 07/17:55:10->07/18:03:54 | 10/16:44:44->10/16:49:24 | -          |
| pronto-proteomes                 | 07/17:55:10->07/18:26:10 | 10/16:44:44->10/17:49:49 | ~30min     |
| pronto-proteins                  | 07/17:55:10->07/18:57:35 | 10/16:44:44->10/19:20:29 | ~2h        |
| pronto-init-matches              | 07/17:55:10->07/17:55:17 | 10/16:44:44->10/16:45:08 | -          |
| pronto-proteins-names            | 07/17:55:10->07/21:57:07 | 10/16:44:44->10/20:48:29 | -          |
| pronto-insert-fmatches           | 07/17:55:41->07/18:11:41 | 10/16:45:14->10/18:02:29 | ~45min     |
| pronto-insert-matches            | 08/03:54:32->08/04:16:14 | 11/02:44:05->11/05:34:52 | ~2h30      |
| pronto-signatures                | 08/03:54:32->08/05:17:50 | 11/02:44:06->11/04:21:19 | ~30min     |
| pronto-insert-signature2proteins | 08/03:54:32->08/04:40:17 | 11/02:44:06->11/05:56:30 | ~2h        |
| pronto-index-matches             | 08/04:16:20->08/08:42:47 | 11/05:34:59->11/12:02:39 | ~2h30      |
| pronto-index-signature2proteins  | 09/12:54:10->09/19:49:59 | 11/05:56:34->11/13:15:23 | -          |

2023-07-24 10:44 UTC, laisecf commented
> > Thank you. I've added a few suggestions, mostly to comply with PEP-8 (max 80 characters/line).
> > It seems that the [CsvIO class](https://github.com/ProteinsWebTeam/pyinterprod/blob/95225efc686b38539c8bb31d7daa14ed5d667a34/pyinterprod/utils/pg.py#L8) is not required anymore. Please delete the implementation and imports.
> > Finally, can you post the run time of Pronto tasks so we can compare performances?
> 
> The run with the executemany takes plus ~10h30
> 
> Task Name	Runtime before	Runtime after	Difference
> pronto-annotations	07/17:55:09->07/18:27:35	10/16:44:43->10/17:05:13	-
> pronto-taxonomy	07/17:55:09->07/17:59:51	10/16:44:43->10/16:52:55	-
> pronto-databases	07/17:55:09->07/17:55:20	10/16:44:44->10/16:44:49	-
> pronto-export-matches	07/17:55:10->08/03:54:16	10/16:44:44->11/02:44:01	-
> pronto-proteins-similarities	07/17:55:10->07/18:03:54	10/16:44:44->10/16:49:24	-
> pronto-proteomes	07/17:55:10->07/18:26:10	10/16:44:44->10/17:49:49	~30min
> pronto-proteins	07/17:55:10->07/18:57:35	10/16:44:44->10/19:20:29	~2h
> pronto-init-matches	07/17:55:10->07/17:55:17	10/16:44:44->10/16:45:08	-
> pronto-proteins-names	07/17:55:10->07/21:57:07	10/16:44:44->10/20:48:29	-
> pronto-insert-fmatches	07/17:55:41->07/18:11:41	10/16:45:14->10/18:02:29	~45min
> pronto-insert-matches	08/03:54:32->08/04:16:14	11/02:44:05->11/05:34:52	~2h30
> pronto-signatures	08/03:54:32->08/05:17:50	11/02:44:06->11/04:21:19	~30min
> pronto-insert-signature2proteins	08/03:54:32->08/04:40:17	11/02:44:06->11/05:56:30	~2h
> pronto-index-matches	08/04:16:20->08/08:42:47	11/05:34:59->11/12:02:39	~2h30
> pronto-index-signature2proteins	09/12:54:10->09/19:49:59	11/05:56:34->11/13:15:23	-

### Considering just pronto tasks that had time difference:
 
**Tasks I didn't change to copy (still executemany because is a little time diff)**
- pronto-proteomes                                 23 22:38:32      23 23:27:55    ~50min
- pronto-signatures                                  24 06:28:28     24 07:58:49    ~1h30

**Changing to copy (improved a lot the time, practically the same as before the dependences update)**
- pronto-proteins                                      24 10:17:58      24 11:37:39     ~1h20   
- pronto-insert-fmatches                         23 22:39:02     23 23:21:45    ~45min
- pronto-insert-matches                          24 06:28:28     24 06:57:48    ~30min
- pronto-insert-signature2proteins         24 06:28:29     24 07:00:33    ~30min
- pronto-index-matches                           24 06:57:52     24 07:26:05    ~30min

2023-07-28 09:29 UTC, matthiasblum requested changes
Looks good. I made a few suggestions, but they are mostly indentation-related. Thanks!

2023-07-28 09:29 UTC, matthiasblum commented on pyinterprod/pronto/proteome.py
> +        for rec in list(iterator.proteomes.values()):
```suggestion
        for rec in iterator.proteomes.values():
```

2023-07-28 09:29 UTC, matthiasblum commented on pyinterprod/pronto/signature.py
> +                """
```suggestion
        sql = """
            INSERT INTO signature (
                accession, database_id, name, description, type, abstract, 
                num_sequences, num_reviewed_sequences, num_complete_sequences, 
                num_complete_reviewed_sequences, num_residues
            ) 
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
        """
```

2023-07-28 09:29 UTC, matthiasblum commented on pyinterprod/pronto/signature.py
> +                """
```suggestion
        sql = """
            INSERT INTO comparison (signature_acc_1, signature_acc_2, 
                                    num_collocations, num_overlaps) 
            VALUES (%s, %s, %s, %s)
        """
```

2023-07-28 09:29 UTC, matthiasblum commented on pyinterprod/pronto/signature.py
> +                """
```suggestion
        sql = """
            INSERT INTO prediction (
                signature_acc_1, signature_acc_2, num_collocations, 
                num_protein_overlaps, num_residue_overlaps
            ) 
            VALUES (%s, %s, %s, %s, %s)
        """
```

2023-08-01 08:45 UTC, laisecf commented
> Looks good. I made a few suggestions, but they are mostly indentation-related. Thanks!

Done! And sorry, I will remember to check indentation before commit

2023-08-01 09:20 UTC, matthiasblum approved these changes

2023-08-01 09:20 UTC, merged