Ibu 10659 update report
ProteinsWebTeam/pyinterprod pull request #34
Opened 2023-11-22 14:02 UTC by laisecf

2023-11-23 15:59 UTC, matthiasblum requested changes
In good shape, thanks.

I've highlighted the few issues I identified.

Other improvements that would be nice:

1. `get_swissprot_descriptions` now returns a list of UniProt accessions for each description, you could return a _set_ of UniProt accessions so we don't need to convert the list to set when comparing descriptions before and after the update
2. once `descr2prots` is populated (mapping between a description and the proteins with this description), its type is `dict[str, set[str]]`. You could transform it to `dict[str, list[str]]` so we don't need to convert the `set` of accessions to a `list` of accessions for each description, like here: https://github.com/ProteinsWebTeam/pyinterprod/blob/07fa5c67a5225d63880c476c6c956e6e55a57a65/pyinterprod/interpro/report.py#L174-L179

2023-11-27 16:26 UTC, laisecf commented on pyinterprod/interpro/report.py
>      # Load entry -> descriptions BEFORE UniProt update
bur desc2prot is used in descriptions "before" and "after" UniProt update

2023-11-27 16:30 UTC, laisecf commented on pyinterprod/interpro/report.py
> +                    continue
you right! this block dont need to be in the internal for

2023-11-27 22:35 UTC, matthiasblum commented on pyinterprod/interpro/report.py
>      # Load entry -> descriptions BEFORE UniProt update
Fair enough.

2023-12-12 20:43 UTC, laisecf commented on pyinterprod/interpro/report.py
> +                     f"\t{len(sig2prots[acc])}\t"
```suggestion
                     f"\t{len(sig2prots[acc])}"
```

2023-12-12 21:06 UTC, matthiasblum requested changes

2023-12-13 10:27 UTC, laisecf commented on pyinterprod/interpro/report.py
> +                     f"\t{' | '.join(gained_descs)}\n")
You're right! I had fixed this and then forgot about it and came back to it when I refactored... sorry for this o/

2023-12-13 13:14 UTC, matthiasblum approved these changes
Looks good! :+1: 
Feel free to merge. :rocket:

2023-12-13 13:44 UTC, merged