Go taxon constraint
ProteinsWebTeam/pyinterprod pull request #37
Opened 2023-12-06 09:35 UTC by laisecf

2023-12-06 09:40 UTC, laisecf commented on pyinterprod/pronto/goa.py
> +                for constr_id in constraints:
About these "for", it's bothering me to have an n^3 despite having very few elements in the internal "for"s. I'm thinking about how to refactor the creation of this dict to improve here.

2023-12-07 10:42 UTC, matthiasblum requested changes
Good overall, with a few issues to resolve.

Also, a few variables could have better names, e.g.

- `union2taxon` should be renamed for consistency with the data it contains, such as `union2taxa` (plural of _taxon_ is _taxa_, and a union is not for _one taxon_)
- `constr_id` is a taxon ID, so better name it `tax_id`, or `taxon_id`.

2023-12-07 10:42 UTC, matthiasblum commented on pyinterprod/pronto/goa.py
> +        union2taxon[union_id] = taxon_ids.split(",")
Cast directly to a `set`:

```suggestion
        union2taxon[union_id] = set(taxon_ids.split(","))
```

2023-12-07 10:42 UTC, matthiasblum commented on pyinterprod/pronto/goa.py
> +            raise f"Unknown TAX_ID_TYPE: {tax_id_type}"
Exceptions must derive from one of the [base exceptions](https://docs.python.org/3/library/exceptions.html) (in this case `ValueError` seems to be the best fit):

```suggestion
            raise ValueError(f"Unknown TAX_ID_TYPE: {tax_id_type}")
```

2023-12-07 10:42 UTC, matthiasblum commented on pyinterprod/pronto/goa.py
> +        SELECT T.GO_ID, AT.GO_ID, TC.RELATIONSHIP, TC.TAX_ID_TYPE, TC.TAX_ID
No need to select columns we don't use:

```suggestion
        SELECT T.GO_ID, TC.RELATIONSHIP, TC.TAX_ID_TYPE, TC.TAX_ID
```

2023-12-07 10:42 UTC, matthiasblum commented on pyinterprod/pronto/goa.py
> +            current_tax_id = {tax_id}
Why not adding directly to `go2constraints[go_id][relationship]`?

2023-12-07 10:42 UTC, matthiasblum commented on pyinterprod/pronto/goa.py
> +                """
Indentation:

```suggestion
        sql = """
            INSERT INTO GO2CONSTRAINTS (go_id, relationship, taxon)
            VALUES (%s, %s, %s)
        """
```

2023-12-07 10:42 UTC, matthiasblum commented on pyinterprod/pronto/goa.py
> +                records.clear()
You need to check for the number of cached records after each `append()`:

```suggestion
                    records.append((go_id, relation, constr_id))

                    if len(records) == 1000:
                        pg_cur.executemany(sql, records)
                        pg_con.commit()
                        records.clear()
```

2023-12-08 10:56 UTC, matthiasblum requested changes
`import_go_constraints()` is not called from anywhere. You need to add a task in [`get_pronto_tasks()`](https://github.com/ProteinsWebTeam/pyinterprod/blob/ae64c0458ef225dd1b2888c7656318456ccd2d15/pyinterprod/cli.py#L13) so constraints are imported when we refresh the Pronto database.

You could rename the `annotations` task to `go-terms`, and name the new task `go-constraints`. The new task does not depend on any other task.

2023-12-08 10:56 UTC, matthiasblum commented on pyinterprod/pronto/goa.py
> +
Need to close the Oracle cursor/connection.

2023-12-08 10:56 UTC, matthiasblum commented on pyinterprod/pronto/goa.py
> +    pg_con = psycopg.connect(**url2dict(pg_url))
The PostgreSQL connection should be opened later, when we need it (just before `with pg_con.cursor() as pg_cur:`).

2023-12-08 10:56 UTC, matthiasblum commented on pyinterprod/pronto/goa.py
> +            records.clear()
Need to:
- Create an index on `go_id`
- Close the PostgreSQL connection

2023-12-11 15:29 UTC, matthiasblum approved these changes
LGTM :rocket:

2023-12-11 15:41 UTC, merged