IBU-10833
ProteinsWebTeam/pyinterprod pull request #39
Opened 2024-03-01 07:40 UTC by HobnobMancer

Add Pfam file parsers, facilitating severance from the Pfam MySQL db.
[JIRA](https://www.ebi.ac.uk/panda/jira/browse/IBU-10833)

Data is retrieved from Pfam files (requiring changes to the `members.config` file):
* `Pfam-A.seed`
* `Pfam-A-full`
* `Pfam-C`
* `Pfam-A.fasta`

The output of the original `get_signatures()` and `get_clans()` functions in the `pfam` module have not been changed.

Not ready for merge atm. All code works, except some Pfam-A accessions are retrieved from `Pfam-C` clans file but are not listed in `Pfam-A-full` and therefore, a `null_full` value cannot be retrieved for these Pfam-A accessions. This needs to be addressed prior to merging.

2024-03-19 11:19 UTC, laisecf commented on pyinterprod/interpro/contrib/pfam.py
>  import MySQLdb.cursors
```suggestion

```

2024-03-19 11:20 UTC, laisecf commented on pyinterprod/interpro/contrib/pfam.py
>  from pyinterprod.utils.pg import url2dict
```suggestion
```

2024-03-19 13:42 UTC, laisecf reviewed
Looks great! I have just some doubts and I included a suggestion to remove unused imports ^^

PS: Did you test it on DEV or TST database?

2024-03-20 11:30 UTC, HobnobMancer commented on pyinterprod/interpro/contrib/pfam.py
> +    except UnicodeDecodeError:
It was a TODO I forgot about. In commit [c4774dd](https://github.com/ProteinsWebTeam/pyinterprod/pull/39/commits/c4774dd32b40314e8ea7395cba04e4dbc48cb1e1) I've made the `UnicodeDecodeError` line specific, so that if a line cannot be decoded, the parser flags this to the user and continues to parse the rest of the file.

2024-03-20 18:02 UTC, laisecf requested changes

2024-03-20 18:02 UTC, laisecf commented on pyinterprod/interpro/contrib/pfam.py
> +    con.close()
```suggestion
    con.commit()
    con.close()
```

2024-03-21 11:25 UTC, laisecf approved these changes

2024-03-25 16:06 UTC, HobnobMancer commented
Added gathering alignment counts (`seed_num`, `rp15_num`, etc. as these are required in [`interpro7dw`](https://github.com/ProteinsWebTeam/interpro7-dw/blob/0d32224f6d398c4cb6178e3044b4d1ab290ba775/interpro7dw/pfam.py#L317-L333)). 

Tested the code and the data is persisted in `IPDEV`, in `INTERPRO.PFAM_DATA`

2024-03-26 12:07 UTC, laisecf approved these changes

2024-03-27 08:11 UTC, merged