Import function literature references in Pronto
ProteinsWebTeam/pyinterprod pull request #40
Opened 2024-03-06 11:46 UTC by laisecf

[Jira ticket](https://www.ebi.ac.uk/panda/jira/browse/IBU-10897)

2024-03-14 11:27 UTC, matthiasblum requested changes
Looks good overall. Please see my comments.

2024-03-14 11:27 UTC, matthiasblum commented on pyinterprod/pronto/protein.py
> +                PUBMED_ID VARCHAR(15) NOT NULL
Store PubMed IDs as integer:

```suggestion
                PUBMED_ID INTEGER NOT NULL
```

2024-03-14 11:27 UTC, matthiasblum commented on pyinterprod/pronto/protein.py
> +            swp_acc = [acc for acc, in ora_cur.fetchall()]
Not needed, we can directly find Swiss-Prot proteins in the UniProt database.

```suggestion
```

2024-03-14 11:27 UTC, matthiasblum commented on pyinterprod/pronto/protein.py
> +                      AND E.ENTRY_TYPE IN (0, 1)
My bad, the query I posted on Jira retrieves records for all UniProtKB entries (Swiss-Prot + TrEMBL). This change restricts the query to Swiss-Prot entries:

```suggestion
                      AND E.ENTRY_TYPE IN = 0
```

2024-03-14 11:27 UTC, matthiasblum commented on pyinterprod/pronto/protein.py
> +                ACCESSION VARCHAR(15) NOT NULL,
To be consistent with other `protein2*` tables:

```suggestion
                PROTEIN_ACC VARCHAR(15) NOT NULL,
```

2024-03-14 16:52 UTC, laisecf commented on pyinterprod/pronto/protein.py
> +                      AND E.ENTRY_TYPE IN = 0
```suggestion
                      AND E.ENTRY_TYPE = 0
```

2024-03-18 12:13 UTC, matthiasblum requested changes
A few changes to make, but getting there.. :)

2024-03-18 12:13 UTC, matthiasblum commented on pyinterprod/pronto/protein.py
> +        reg_pubmed = re.compile(r"(PubMed:(\d+))")
It is not necessary to compile patterns when there are only  a few regular expression(s) used (in this case _one_), you can simply use `re.findall(pattern, string)`.

2024-03-18 12:13 UTC, matthiasblum commented on pyinterprod/pronto/protein.py
> +                for pmid in pmids:
`findall()` returns a list (empty if no matches found), so you don't need to check whether it evaluates to true or false, you can directly iterate. Also your pattern captures two groups, so `pmids` is list of tuples. By capture the PMID only, `findall()` returns a list of  strings.

```suggestion
            for pmid in re.findall(r"PubMed:(\d+)", text):
```

2024-03-18 12:13 UTC, matthiasblum commented on pyinterprod/pronto/protein.py
> +                    swp2pmid.add((acc, pmid[1]))
Explicit >> Implicit. Convert the string-representation of PMIDs to integers.
```suggestion
                    swp2pmid.add((acc, int(pmid[1])))
```

2024-03-18 12:13 UTC, matthiasblum commented on pyinterprod/pronto/protein.py
> +                        swp2pmid.clear()
This is a good approach for avoiding keeping a lot of records in memory, but there won't be so many records (total around 100k), so we can keep everything in memory and insert all records at once.

```suggestion
```

2024-03-18 12:13 UTC, matthiasblum commented on pyinterprod/pronto/protein.py
> +            pg_cur.executemany(sql, swp2pmid)
Since `executemany()` will be called once only, you can directly pass the SQL statement as a string instead of storing in the `sql` variable.

2024-03-18 12:13 UTC, matthiasblum commented on pyinterprod/pronto/protein.py
> +    ora_con.close()
Oracle connection should be closed immediately after we don't need it anymore.

2024-03-18 14:13 UTC, laisecf commented
> A few changes to make, but getting there.. :)

Thank you for the tips, Matthias! The code is much more clear/concise now

2024-03-18 16:54 UTC, merged