Get repr domains
ProteinsWebTeam/pyinterprod pull request #41
Opened 2024-03-12 15:22 UTC by laisecf

2024-03-18 10:46 UTC, matthiasblum requested changes
Thank you. Please see my comments.

2024-03-18 10:46 UTC, matthiasblum commented on pyinterprod/uniprot/unirule.py
> +REPR_DOM_DATABASES = ["H", "J", "M", "R", "N"]
Unnecessary (not used)

```suggestion
```

2024-03-18 10:46 UTC, matthiasblum commented on pyinterprod/uniprot/unirule.py
> +}
Unnecessary (not needed)

```suggestion
```

2024-03-18 10:46 UTC, matthiasblum commented on pyinterprod/uniprot/unirule.py
> +            "dc-status": DC_STATUSES['S']  # Continuous
The character cote of is enough for `dc-status`:

```suggestion
                "dc-status": t
            })

        result.sort(key=lambda x: (x["start"], x["end"]))
    else:
        result = [{
            "start": pos_start,
            "end": pos_end,
            "dc-status": "S"  # Continuous
```

2024-03-18 10:46 UTC, matthiasblum commented on pyinterprod/uniprot/unirule.py
> +                    )
So `proteins_domains` is always going to have one key-value pair only? It's not very elegant. You can keep a `previous_protein_acc` variable, and compare it with `protein_acc`, e.g.

```py
previous_protein_acc = None
domains = []
for protein_acc, signature_acc, model_acc, dbcode, pos_start, pos_end, frags in cur:
  if protein_acc != previous_protein_acc:
    # select representative domains from `domains`
    ...
    # then reset `domains`
    domains = []
    # and update `previous_protein_acc`
    previous_protein_acc = protein_acc

  # add the match to `domains`
  domains.append({
  ...
  })
```

2024-03-18 10:46 UTC, matthiasblum commented on pyinterprod/uniprot/unirule.py
> +                                f"{current_protein}\t{domain['signature']}\t{domain['model']}\t{domain['fragments']}\t{domain['representative']}\n"
`domain['fragments']` is a list of dicts and its string representation (e.g. when written to a file) is something like `[{'start': 137, 'end': 201, 'dc-status': 'CONTINUOUS'}]`. This is not even a valid JSON string as JSON allows double quotes only to enclose property names.

Also, `domain['representative']` is not necessary as you're only writing representative domains (so this column will only have `True` values).

The values in the output should be:

1. protein accession
2. signature accession
3. start position _of the match_
4. end position _of the match_
5. string representation _of the fragments_ (e.g. `112-136-C,202-327-N`)

I don't think we need the model.

2024-03-18 10:46 UTC, matthiasblum commented on pyinterprod/uniprot/unirule.py
> +        SELECT PROTEIN_AC, H.METHOD_AC, MODEL_AC, H.DBCODE,
Unnecessary (not used):

```suggestion
        SELECT PROTEIN_AC, H.METHOD_AC, MODEL_AC,
```

2024-03-18 14:41 UTC, laisecf commented on pyinterprod/uniprot/unirule.py
> +REPR_DOM_DATABASES = ["H", "J", "M", "R", "N"]
this one is used to the rank (we get the index)

2024-03-18 14:42 UTC, laisecf commented on pyinterprod/uniprot/unirule.py
> +                    )
so simpler 🤦🏻‍♀️ thank you!

2024-03-18 14:56 UTC, laisecf commented on pyinterprod/uniprot/unirule.py
> +REPR_DOM_DATABASES = ["H", "J", "M", "R", "N"]
ah, ok! the output dont need the rank. Got it o/

2024-03-18 16:01 UTC, laisecf commented on pyinterprod/uniprot/unirule.py
> +REPR_DOM_DATABASES = ["H", "J", "M", "R", "N"]
sorry, but we need to calculate the repr. domains 😅

2024-03-20 10:53 UTC, HobnobMancer reviewed
Looks good to me! Just a couple of potential minor tweaks

2024-03-20 10:53 UTC, HobnobMancer commented on pyinterprod/uniprot/unirule.py
> +    return False
Optional: The code could be shortened and reduce the number of times of calculating the lengths? 
```suggestion
def _eval_overlap(dom_a: dict, dom_b: dict, threshold: float) -> bool:
    overlap = len(dom_a["residues"] & dom_b["residues"])
    return overlap and overlap / min(len(dom_a["residues"]), len(dom_b["residues"])) >= threshold
```

2024-03-21 12:29 UTC, HobnobMancer approved these changes
Looks good to me :smiley:  just one minor change to avoid direct injection on a query.

2024-03-21 12:29 UTC, HobnobMancer commented on pyinterprod/uniprot/unirule.py
> +    )
You're right my last suggestion had a mistake in it, as I forgot that Oracle does not support binding a Python tuple to an SQL `IN` clause directly :sweat_smile: 

It might be better to avoid a direct injection of the values in `REPR_DOM_DATABASES` into the query. You can do this with dynamically creating a string of placeholders for the `IN` clause. E.g:
```suggestion
    placeholders = ', '.join(':' + str(i + 1) for i in range(len(REPR_DOM_DATABASES)))
    params = {str(i + 1): db for i, db in enumerate(REPR_DOM_DATABASES)}
    cur.execute(
        f"""
        SELECT PROTEIN_AC, H.METHOD_AC, H.DBCODE, POS_FROM, POS_TO, FRAGMENTS
        FROM INTERPRO.MATCH H
        INNER JOIN INTERPRO.METHOD D
        ON H.METHOD_AC = D.METHOD_AC
        WHERE H.DBCODE in ({placeholders})
        AND (D.SIG_TYPE = 'D' OR D.SIG_TYPE = 'R')
        ORDER BY PROTEIN_AC
        """, params
    )
   
```

2024-03-22 09:57 UTC, laisecf commented on pyinterprod/uniprot/unirule.py
> +    )
Ah! Even better, thank you!

2024-03-25 16:46 UTC, matthiasblum approved these changes
Looks good. I made a few minor suggestions. Please have a look and incorporate suggestions you agree with.

2024-03-25 16:46 UTC, matthiasblum commented on pyinterprod/uniprot/unirule.py
> +REPR_DOM_DATABASES = ["H", "J", "M", "R", "N"]
I didn't realise these aren't at the beginning of the file. Please move then after the imports.

2024-03-25 16:46 UTC, matthiasblum commented on pyinterprod/uniprot/unirule.py
> +
PEP-8 + use a position bind by directly using `REPR_DOM_DATABASES` (it's a list, so the elements of the list will be used as bind values):

```suggestion
    placeholders = ','.join(':' + str(i + 1)
                            for i in range(len(REPR_DOM_DATABASES)))
    cur.execute(
        f"""
        SELECT PROTEIN_AC, H.METHOD_AC, H.DBCODE, POS_FROM, POS_TO, FRAGMENTS
        FROM INTERPRO.MATCH H
        INNER JOIN INTERPRO.METHOD D
        ON H.METHOD_AC = D.METHOD_AC
        WHERE H.DBCODE in ({placeholders})
        AND (D.SIG_TYPE = 'D' OR D.SIG_TYPE = 'R')
        ORDER BY PROTEIN_AC
        """,
        REPR_DOM_DATABASES
    )

```

2024-03-25 16:46 UTC, matthiasblum commented on pyinterprod/uniprot/unirule.py
> +                    )
PEP 8 (line too long)

```suggestion
                    f.write(
                        f"{previous_protein_acc}\t{domain['signature']}\t"
                        f"{domain['start']}\t{domain['end']}\t"
                        f"{domain['frag']}\n"
                    )
```

2024-03-25 16:46 UTC, matthiasblum commented on pyinterprod/uniprot/unirule.py
> +                )
PEP 8 (line too long)

```suggestion
                f.write(
                    f"{protein_acc}\t{domain['signature']}\t{domain['start']}\t"
                    f"{domain['end']}\t{domain['frag']}\n"
                )
```

2024-03-25 16:46 UTC, matthiasblum commented on pyinterprod/uniprot/unirule.py
> +    return overlap and overlap / min(len(dom_a["residues"]), len(dom_b["residues"])) >= threshold
PEP 8 (line too long)

```suggestion
    return overlap and overlap / min(len(dom_a["residues"]),
                                     len(dom_b["residues"])) >= threshold
```

2024-03-26 10:48 UTC, merged