Refactor Pfam data persistence
ProteinsWebTeam/pyinterprod pull request #45
Opened 2024-04-17 09:08 UTC by matthiasblum

- Implement a generic Stockholm format parser to extract relevant information from:
  - `Pfam-A.seed.gz`
  - `Pfam-A.full.gz`
  - `Pfam-C.gz`
- Remove code related to UniProt/RP15/RP35/RP55/RP75, which are no longer supported in the InterPro website.
- Retrieve alignments directly from `Pfam-A.seed.gz` and `Pfam-A.full.gz` instead of individual files.
- Simplify persistence by dumping all required data into two tables: `PFAM_A` (families) and `PFAM_C` (clans). Alignments are stored gzip-compressed.

`PFAM_A` and `PFAM_C` tables created on `IPTST` (using Pfam 37.0 data).

2024-04-18 10:20 UTC, HobnobMancer requested changes
Generally looks good :smiley: 
There's a couple of issues with handling missing data, which I've flagged

2024-04-18 14:26 UTC, matthiasblum commented on pyinterprod/interpro/contrib/pfam.py
> +                rn2pmid[i+1] = int(obj["RM"])
Using ` int(" ".join(obj["RM"]))` so a ValueError is raised when there are two PMIDs or more.

2024-04-19 08:42 UTC, laisecf commented on pyinterprod/interpro/clan.py
> +        clans = contrib.pfam.get_clans(kwargs["clan"],
```suggestion
        clans = contrib.pfam.get_clans(kwargs["clans"],
```

2024-04-19 12:01 UTC, HobnobMancer approved these changes
LGTM

2024-04-19 13:27 UTC, laisecf approved these changes
Great refactoring!! 🎉  Everything running perfectly in the latest tests

2024-04-19 15:02 UTC, merged