Replace refs on clan CC lines
ProteinsWebTeam/pyinterprod pull request #50
Opened 2024-12-03 13:45 UTC by tgrego

references on clan comments now get a reference replacement just like the pfam comments, so [1,2] becomes something like [PMID:111,PMID:222].

References in the form [1-3] were ignored, this also fixes that so they become something like [PMID:111,PMID:222,PMID:333]

2024-12-05 12:02 UTC, matthiasblum requested changes
Thanks. Minor changes required, please see comments/suggestions.

2024-12-06 15:11 UTC, tgrego commented
updated based on comments/suggestions, thanks!

2024-12-09 13:39 UTC, matthiasblum approved these changes
I made a minor change. Feel free to merge.

2024-12-09 13:39 UTC, matthiasblum commented on pyinterprod/interpro/contrib/pfam.py
> +    return(r)
Blank line before `return`, and also `return` is a statement and doesn't need parentheses, unless you want to return a tuple.

```suggestion

    return r
```

2024-12-09 14:36 UTC, merged